// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 同步玩家ID msgid=1
type SyncPid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"` //服务器生成新玩家
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPid) Reset() {
	*x = SyncPid{}
	mi := &file_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPid) ProtoMessage() {}

func (x *SyncPid) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPid.ProtoReflect.Descriptor instead.
func (*SyncPid) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *SyncPid) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// 广播 msgid=200
type Broadcast struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pid   int32                  `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	Tp    int32                  `protobuf:"varint,2,opt,name=Tp,proto3" json:"Tp,omitempty"` //1-世界聊天；2-玩家位置 3-动作 4-移动后的位置更新
	// Types that are valid to be assigned to Data:
	//
	//	*Broadcast_Content
	//	*Broadcast_Pos
	//	*Broadcast_ActionData
	Data          isBroadcast_Data `protobuf_oneof:"Data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broadcast) Reset() {
	*x = Broadcast{}
	mi := &file_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast) ProtoMessage() {}

func (x *Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast.ProtoReflect.Descriptor instead.
func (*Broadcast) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *Broadcast) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Broadcast) GetTp() int32 {
	if x != nil {
		return x.Tp
	}
	return 0
}

func (x *Broadcast) GetData() isBroadcast_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Broadcast) GetContent() string {
	if x != nil {
		if x, ok := x.Data.(*Broadcast_Content); ok {
			return x.Content
		}
	}
	return ""
}

func (x *Broadcast) GetPos() *Position {
	if x != nil {
		if x, ok := x.Data.(*Broadcast_Pos); ok {
			return x.Pos
		}
	}
	return nil
}

func (x *Broadcast) GetActionData() int32 {
	if x != nil {
		if x, ok := x.Data.(*Broadcast_ActionData); ok {
			return x.ActionData
		}
	}
	return 0
}

type isBroadcast_Data interface {
	isBroadcast_Data()
}

type Broadcast_Content struct {
	Content string `protobuf:"bytes,3,opt,name=Content,proto3,oneof"` //聊天内容
}

type Broadcast_Pos struct {
	Pos *Position `protobuf:"bytes,4,opt,name=Pos,proto3,oneof"` //位置
}

type Broadcast_ActionData struct {
	ActionData int32 `protobuf:"varint,5,opt,name=ActionData,proto3,oneof"` //动作
}

func (*Broadcast_Content) isBroadcast_Data() {}

func (*Broadcast_Pos) isBroadcast_Data() {}

func (*Broadcast_ActionData) isBroadcast_Data() {}

// 位置信息
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
	V             float32                `protobuf:"fixed32,4,opt,name=V,proto3" json:"V,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Position) GetV() float32 {
	if x != nil {
		return x.V
	}
	return 0
}

// 世界聊天
type Talk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Talk) Reset() {
	*x = Talk{}
	mi := &file_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Talk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Talk) ProtoMessage() {}

func (x *Talk) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Talk.ProtoReflect.Descriptor instead.
func (*Talk) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *Talk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SyncPlayers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ps            []*Players             `protobuf:"bytes,1,rep,name=ps,proto3" json:"ps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPlayers) Reset() {
	*x = SyncPlayers{}
	mi := &file_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPlayers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPlayers) ProtoMessage() {}

func (x *SyncPlayers) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPlayers.ProtoReflect.Descriptor instead.
func (*SyncPlayers) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{4}
}

func (x *SyncPlayers) GetPs() []*Players {
	if x != nil {
		return x.Ps
	}
	return nil
}

type Players struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	Pos           *Position              `protobuf:"bytes,2,opt,name=Pos,proto3" json:"Pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Players) Reset() {
	*x = Players{}
	mi := &file_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Players) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Players) ProtoMessage() {}

func (x *Players) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Players.ProtoReflect.Descriptor instead.
func (*Players) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{5}
}

func (x *Players) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Players) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

var File_msg_proto protoreflect.FileDescriptor

const file_msg_proto_rawDesc = "" +
	"\n" +
	"\tmsg.proto\x12\x02pb\"\x1b\n" +
	"\aSyncPid\x12\x10\n" +
	"\x03Pid\x18\x01 \x01(\x05R\x03Pid\"\x95\x01\n" +
	"\tBroadcast\x12\x10\n" +
	"\x03Pid\x18\x01 \x01(\x05R\x03Pid\x12\x0e\n" +
	"\x02Tp\x18\x02 \x01(\x05R\x02Tp\x12\x1a\n" +
	"\aContent\x18\x03 \x01(\tH\x00R\aContent\x12 \n" +
	"\x03Pos\x18\x04 \x01(\v2\f.pb.PositionH\x00R\x03Pos\x12 \n" +
	"\n" +
	"ActionData\x18\x05 \x01(\x05H\x00R\n" +
	"ActionDataB\x06\n" +
	"\x04Data\"B\n" +
	"\bPosition\x12\f\n" +
	"\x01X\x18\x01 \x01(\x02R\x01X\x12\f\n" +
	"\x01Y\x18\x02 \x01(\x02R\x01Y\x12\f\n" +
	"\x01Z\x18\x03 \x01(\x02R\x01Z\x12\f\n" +
	"\x01V\x18\x04 \x01(\x02R\x01V\" \n" +
	"\x04Talk\x12\x18\n" +
	"\aContent\x18\x01 \x01(\tR\aContent\"*\n" +
	"\vSyncPlayers\x12\x1b\n" +
	"\x02ps\x18\x01 \x03(\v2\v.pb.PlayersR\x02ps\";\n" +
	"\aPlayers\x12\x10\n" +
	"\x03Pid\x18\x01 \x01(\x05R\x03Pid\x12\x1e\n" +
	"\x03Pos\x18\x02 \x01(\v2\f.pb.PositionR\x03PosB\fZ\x05./;pb\xaa\x02\x02Pbb\x06proto3"

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData []byte
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)))
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_msg_proto_goTypes = []any{
	(*SyncPid)(nil),     // 0: pb.SyncPid
	(*Broadcast)(nil),   // 1: pb.Broadcast
	(*Position)(nil),    // 2: pb.Position
	(*Talk)(nil),        // 3: pb.Talk
	(*SyncPlayers)(nil), // 4: pb.SyncPlayers
	(*Players)(nil),     // 5: pb.Players
}
var file_msg_proto_depIdxs = []int32{
	2, // 0: pb.Broadcast.Pos:type_name -> pb.Position
	5, // 1: pb.SyncPlayers.ps:type_name -> pb.Players
	2, // 2: pb.Players.Pos:type_name -> pb.Position
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	file_msg_proto_msgTypes[1].OneofWrappers = []any{
		(*Broadcast_Content)(nil),
		(*Broadcast_Pos)(nil),
		(*Broadcast_ActionData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
